// Code generated by "stringer -type=LmTempType"; DO NOT EDIT.

package lmsensors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Disabled-0]
	_ = x[CPUDiode-1]
	_ = x[Transistor-2]
	_ = x[ThermalDiode-3]
	_ = x[Thermistor-4]
	_ = x[AMDSI-5]
	_ = x[IntelPECI-6]
	_ = x[Unknown-2147483647]
}

const (
	_LmTempType_name_0 = "DisabledCPUDiodeTransistorThermalDiodeThermistorAMDSIIntelPECI"
	_LmTempType_name_1 = "Unknown"
)

var (
	_LmTempType_index_0 = [...]uint8{0, 8, 16, 26, 38, 48, 53, 62}
)

func (i LmTempType) String() string {
	switch {
	case 0 <= i && i <= 6:
		return _LmTempType_name_0[_LmTempType_index_0[i]:_LmTempType_index_0[i+1]]
	case i == 2147483647:
		return _LmTempType_name_1
	default:
		return "LmTempType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
