// Code generated by "stringer -type=SensorType"; DO NOT EDIT.

package lmsensors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Voltage-0]
	_ = x[Fan-1]
	_ = x[Temperature-2]
	_ = x[Power-3]
	_ = x[Energy-4]
	_ = x[Current-5]
	_ = x[Humidity-6]
	_ = x[VID-16]
	_ = x[Intrusion-17]
	_ = x[BeepEnable-24]
	_ = x[Unhandled-2147483647]
}

const (
	_SensorType_name_0 = "VoltageFanTemperaturePowerEnergyCurrentHumidity"
	_SensorType_name_1 = "VIDIntrusion"
	_SensorType_name_2 = "BeepEnable"
	_SensorType_name_3 = "Unhandled"
)

var (
	_SensorType_index_0 = [...]uint8{0, 7, 10, 21, 26, 32, 39, 47}
	_SensorType_index_1 = [...]uint8{0, 3, 12}
)

func (i SensorType) String() string {
	switch {
	case 0 <= i && i <= 6:
		return _SensorType_name_0[_SensorType_index_0[i]:_SensorType_index_0[i+1]]
	case 16 <= i && i <= 17:
		i -= 16
		return _SensorType_name_1[_SensorType_index_1[i]:_SensorType_index_1[i+1]]
	case i == 24:
		return _SensorType_name_2
	case i == 2147483647:
		return _SensorType_name_3
	default:
		return "SensorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
