// Code generated by "stringer -type=TempType"; DO NOT EDIT.

package golmsensors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Disabled-0]
	_ = x[CPUDiode-1]
	_ = x[Transistor-2]
	_ = x[ThermalDiode-3]
	_ = x[Thermistor-4]
	_ = x[AMDSI-5]
	_ = x[IntelPECI-6]
}

const _TempType_name = "DisabledCPUDiodeTransistorThermalDiodeThermistorAMDSIIntelPECI"

var _TempType_index = [...]uint8{0, 8, 16, 26, 38, 48, 53, 62}

func (i TempType) String() string {
	if i < 0 || i >= TempType(len(_TempType_index)-1) {
		return "TempType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TempType_name[_TempType_index[i]:_TempType_index[i+1]]
}
